### ISSUE TITLE
How does spellcorrect work?

### ISSUE THREAD

**Issue by howardyclo** [jbhoosreddy/spellcorrect#2]
Hello, thanks for the nice repo.
What papers/references you referenced when implementing this work?
I'm wondering how does this implementation work. Thanks.

**Comment by matanox** [comment]
Yeah would be nice noting how the different well-known algorithms work in harmony here, even if not citing any paper for that (I doubt a research paper is needed for that). I guess the code should be self-explanatory too.

**Comment by jbhoosreddy** [comment]
I've updated the readme to clearly emphasize which paper this implementation is based on. Feel free to reopen this issue if there are other questions.
